### ISSUE TITLE
HEAD Request not Working

### ISSUE THREAD

**Issue by pablocrivella** [intridea/grape#1014] opened 2015-05-08 21:25 UTC
```
Started HEAD "/v1/status/" for 10.0.2.2 at 2015-05-08 21:17:02 +0000

ActionController::RoutingError (No route matches [HEAD] "/v1/status"):
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  rack-mini-profiler (0.9.3) lib/mini_profiler/profiler.rb:276:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  puma (2.11.2) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.2) lib/puma/server.rb:375:in `process_client'
  puma (2.11.2) lib/puma/server.rb:262:in `block in run'
  puma (2.11.2) lib/puma/thread_pool.rb:104:in `call'
  puma (2.11.2) lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

routes.rb

````ruby
Rails.application.routes.draw do
  # use_doorkeeper
  get '/' => redirect('/documentation')

  mount GrapeSwaggerRails::Engine => '/documentation'
  mount Api::Base => '/'
end
```
```ruby
module Api
  module V1
    class Status < Grape::API
      include Api::V1::Defaults

      desc 'Return status for ELB', hidden: true

      get '/status' do
        { time: Time.zone.now.to_s }
      end
    end
  end
end
```

```ruby
# ruby 2.2.1
gem 'rails', '~> 4.2.0'
gem 'grape', '~> 0.11.0'
```

**Comment by pablocrivella** [comment] 2015-05-08 21:34
could this be related? 
https://github.com/rails/rails/issues/18698
I also tried mounting the API on /api' but the error persists.

**Comment by dblock** [comment] 2015-05-09 01:52
And https://github.com/rails/rails/pull/19431.

**Comment by dblock** [comment] 2015-05-09 01:53
It would be nice to get a (failing) test for this in https://github.com/dblock/grape-on-rails.

**Comment by Fjan** [comment] 2015-05-25 08:49
I ran into this too. It's easy to reproduce, a HEAD request in an integration test will fail on any route with :via => :all, for example:
`match '/:controller(/:action(/:id))',  :via => :all`

A quick fix to make it work is to enumerate the verbs you support, for example:
`match '/:controller(/:action(/:id))',  :via => [:get, :post, :delete, :head]`

**Comment by Fjan** [comment] 2015-05-25 10:34
I just confirmed that this is fixed by https://github.com/rails/rails/pull/19431 I suggest we track this there

**Comment by dblock** [comment] 2015-05-25 16:00
Since this is a Rails bug I am going to close this.

**Closed by dblock** 2015-05-25 16:00 UTC
Labels: bug?
