### ISSUE TITLE
Memory leak under Rack::Test

### ISSUE THREAD

**Issue by mattsnyder** [intridea/grape#665] opened 2014-06-27 21:27 UTC
We've been writing our API using Grape and the DSL is great! However as we write more endpoints and test them with RSpec we've seen memory utilization skyrocket! Upwards of 8+G to test ~7 endpoints!

I wrote a spec file to try and isolate the problem and noticed three classes that with every call to an endpoint leave behind numerous objects that cannot be garbage collected.

Here is the spec I wrote that shows the increase in references for these classes:
`Grape::Route`, `Grape::Endpoint`,`Grape::Util::HashStack`,`Regexp`

And after 3 calls to the endpoint, I saw the reference counts go from
```
"Grape::Route 25 references"
"Grape::Endpoint 36 references"
"Grape::Util::HashStack 50 references"
"Regexp 4386 references"
```

to

```
"Grape::Route 47 references"
"Grape::Endpoint 47 references"
"Grape::Util::HashStack 60 references"
"Regexp 4687 references"
```

```ruby
require 'spec_helper'

class GcApi < Grape::API
  prefix 'gcapi'
  format :json

  resources :testing do
    get do
      true
    end

    put do
      false
    end
  end
end

UserTesting::Orders::Application.routes.draw do
  mount GcApi => '/'
end


describe GcApi do
 include Rack::Test::Methods
 def app
   subject
 end

  def log(object, message)
    header = "*"*20 + message + "*"*20
    p header
    p object
    p "*"*header.length
  end

  def dumpit(file)
    counts = Hash.new{ 0 }
    ObjectSpace.each_object do |o|
      counts[o.class] += 1
    end
    file = File.open(file, 'w')
    counts.each do |key, val|
      file.puts(key.to_s + "=" + val.to_s)
    end
    file.close
  end

  def show_references(klass)
    count = 0
    ObjectSpace.each_object(klass) do |o|
      count += 1
    end
    p klass.to_s + " #{count} references"
  end

  def accept_header
    { 'HTTP_ACCEPT' => "application/json" }
  end

  before(:all) do
    GC.start
    log ObjectSpace.count_objects, "BEFOREALL"
    # dumpit("before.txt")
    show_references(Grape::Route)
    show_references(Grape::Endpoint)
    show_references(Grape::Util::HashStack)
    show_references(Regexp)
  end

  after(:all) do
    show_references(Grape::Route)
    show_references(Grape::Endpoint)
    show_references(Grape::Util::HashStack)
    show_references(Regexp)
    GC.start
    log ObjectSpace.count_objects, "AFTERALL"
    # dumpit("after.txt")
  end

  it "should run quickly" do #1635
    get "/gcapi/testing.json", nil, {}
    last_response.body.should == "true"
  end

  it "should run longer" do #1635
    get "/gcapi/testing.json", nil, {}
    last_response.should be_empty # false assumption
  end

  it "should run quickly or maybe not" do #409
    put "/gcapi/testing.json", nil, {}
    last_response.body.should == "false"
  end

  # it "should be able to GC" do
  #   GC.start
  #   sleep 5
  #   log ObjectSpace.count_objects, "BEFORESIMPLETEST"
  #   (1+1).should eql(2)
  #   GC.start
  #   sleep 5
  #   log ObjectSpace.count_objects, "AFTERSIMPLETEST"
  # end
end
```

**Comment by dblock** [comment] 2015-01-02 18:27
@slauwers @mattsnyder I spent a bit of time on this, using code in https://github.com/dblock/grape-on-rack/pull/8.

First, I cannot reproduce the fact that every `get` generates a new Endpoint reference (or anything runaway). Make sure to add `GC.start` in an `after` block to get consistent output.

``` ruby
  after(:all) do
    GC.start
    @stats.collect!
    @stats.display
  end
```

I can however consistently reproduce that every time we declare an API it doesn't get GC-ed between tests. This is normal, if you're going to create a new type that inherits from `Grape::API`, it mounts endpoints and holds onto them. But that's not a leak.

``` ruby
module Acme
  class API < Grape::API
  ...
  end
end
```

Here `Acme::API` will hold onto its endpoints every time, you can examine `Acme::API.endpoints` to see them.

Help me see a leak here where iterating over something produces a very large number of allocated objects?

**Comment by mattsnyder** [comment] 2015-01-03 23:54
I was only seeing it under test

**Comment by dblock** [comment] 2015-01-04 01:16
@mattsnyder That's totally fine, I *still* would like a way to see it myself ;)

**Comment by slauwers** [comment] 2015-01-05 10:46
@dblock Having a look at this now. Will get back to you ASAP.

**Comment by slauwers** [comment] 2015-01-05 13:56
@dblock Indeed, this may not have been clear in my previous comments, I was unable to reproduce an issue where upon each GET request there was un-GC'd data. I tried from fresh to try and isolate something, however was unsure whether what I was showing was a leak or not. Hence my comment:

> Is this sufficient to show that there is a leak, or do you need me to dig in further?

I do however notice this problem (the leaks) in my software. I can't post results of OStats on my software, considering I'm using Sequel and this seems to mess with `o.class.name`; I'm getting a lot of nil errors if I attempt to use OStat.

I can't work on this any further today, however I'll try to clear some time during the week to reproduce the issue in test. Sorry for the waste of time.

**Comment by dblock** [comment] 2015-01-05 23:10
Thanks @slauwers, looking forward to hearing from you.

**Comment by yr0** [comment] 2015-04-01 08:22
For anyone having similar trouble and thinking it is Grape's memory leak, please check if you are not doing what is described below.

Here's rough reproduction of what seems like a Grape leak:


    require 'grape'
    require 'rack/test'
  
    class TestCl < Grape::API
      prefix "api"
  
      get do
      end
    end
  
    describe TestCl do
      include Rack::Test::Methods
  
      let(:app) { subject }
  
      100.times do
        it "returns all when get '/'" do
          get "api/"
          expect(1).to eq 1
        end
      end
  
    end

The specs above gradually slow down to almost-infinity devouring away your resources.
Here's how to 'fix' it:

    require 'grape'
    require 'rack/test'
  
    class TestCl < Grape::API
      prefix "api"
  
      get do
      end
    end
  
    describe "TestCl" do
      include Rack::Test::Methods
  
      let(:app) { TestCl }
  
      100.times do
        it "returns all when get '/'" do
          get "api/"
          expect(1).to eq 1
        end
      end
  
    end

I.e. point the `app` to your actual `Grape::API` class, and not to the `subject` reference.

**Comment by slauwers** [comment] 2015-04-01 09:27
@yr0 Thanks a bunch. This has indeed solved the problem I was having. @dblock, I guess we can close this one.

**Comment by dblock** [comment] 2015-04-01 12:06
This makes sense. Every time you use `subject` it creates an instance of `TestCl`, which does work, but never gets GCed and is not what you're supposed to use since Grape APIs are classes, not instances. I'd appreciate if @slauwers and @yr0 could quickly parse through Grape tests and README and see if we do this anywhere and potentially PR some doc. Otherwise I think it's one of those gotchas and people will make this "mistake" anyway. Closing this issue.

**Closed by dblock** 2015-04-01 12:06 UTC
Labels: bug?

**Comment by slauwers** [comment] 2015-04-01 12:31
@grape: I'm in the process of leaving the company this account is linked
to, so doing any kind of work on this during business hours is going to be
tricky. I'll see if I can work through this in my spare time, on my
@teotwaki account.
