### ISSUE TITLE
rescue_from :all  &  Grape::Exceptions::ValidationErrors

### ISSUE THREAD

**Issue by johnsinco** [intridea/grape#938] opened 2015-02-24 14:19 UTC
I was writing an integration test of our API and was having trouble understanding why I was getting a 500 response code on validation tests instead of the 400 response I was expecting.  Eventually I tracked it to our use of `rescue_from :all`.  

It would be cool if we could still use `rescue_from :all` but for situations where the error is a validation error the returning response code would be a 400?  

Thanks!!

**Comment by johnsinco** [comment] 2015-02-24 22:56
Upon further debugging today, we discovered that error.error_response doesn't allow the status code to be passed thru from the source error when you do a rescue_from :all, and do not specify a block for it.  So a validation error that would otherwise return a 400 status returns the default 500 status code.

https://github.com/intridea/grape/blob/873f801440ba0c08e4627d784f2865ffc0de0302/lib/grape/middleware/error.rb#L65

**Comment by dblock** [comment] 2015-02-25 12:05
I am going to close this by design, added some explanation in #939. For context here, `rescue_all`'s purpose is exactly to trap all exceptions and handle them in a uniform way, shortcutting any other decisions about status codes and such. It's a catch all. 

If you want to return a 400 validation error with a catch-all, handle those explicitly via a `rescue_from Grape::Exceptions::Validations`.

I can see the opposite argument here, but I also want to mention that this would be a pretty major behavior change for existing APIs and you can already achieve what you want with existing code. 

Please do let me know if I missed something!

**Closed by dblock** 2015-02-25 12:05 UTC

**Comment by tian-xiaobo** [comment] 2015-03-16 06:50
@johnsinco 
 If you want to return a 400 validation error with a catch-all, handle those explicitly via a
 rescue_from Grape::Exceptions::ValidationErrors do |e|
      error_response(message: e.message, status: 406)
 end
